import ContactForm from 'modules/contact';
import Navigation from 'components/Navigation';
import Footer from 'components/Footer';
import MiniHero from 'components/MiniHero';
import Head from 'next/head';

const Contact = () => (
  <>
    <Head>
      <title>NV Nekretnine | Kontakt</title>
      <meta content="Generated by create next app" name="description" />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <link href="/favicon.png" rel="shortcut icon" />
      <script
        async
        defer
        src={`https://www.google.com/recaptcha/api.js?render=${process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY}`}
      />
    </Head>

    <Navigation />
    <MiniHero
      alt="Građevinsko preduzeće"
      bgImageSrc="/img/sales.jpg"
      title="Kontaktirajte nas"
    />
    <ContactForm />
    <Footer />
  </>
);

export default Contact;
